name: Publish library packages

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Perform release build
      run: |
        ./gradlew assembleRelease
    - name: Publish libraries on Github Packages
      env:
        GH_USERNAME: xeffyr
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        ./gradlew publish
