name: Test app

on:
  workflow_dispatch

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Execute tests
      run: |
        ./gradlew test
