name: Test app

on:
  workflow_dispatch

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Execute tests
      run: |
        ./gradlew test
