name: Test app

on:
  workflow_dispatch:
    inputs:
      caption:
        description: "Workflow caption:"
        required: false
        default: "HELLO WORLD!"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  testing:
    caption:${{ github.event.inputs.caption }}
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Execute tests
      run: |
        ./gradlew test
